### ISSUE TITLE
java.lang.RuntimeException: 2 applicable implementations found for de.q60.mps.explorer.pf.TraceBuilders_base.buildTrace(EditorCell_Collection [EditorCell_Collection])

### ISSUE THREAD

**Issue by alexanderpann** [JetBrains/MPS-extensions#1004]
java.lang.RuntimeException: 2 applicable implementations found for de.q60.mps.explorer.pf.TraceBuilders_base.buildTrace(EditorCell_Collection [EditorCell_Collection])
	at d.q.m.polymorphicfunctions.runtime//de.q60.mps.polymorphicfunctions.runtime.DefaultPFContext.callFunctions(DefaultPFContext.java:43)
	at d.q.m.polymorphicfunctions.runtime//de.q60.mps.polymorphicfunctions.runtime.DefaultPFContext.callFunction(DefaultPFContext.java:32)
	at d.q.m.polymorphicfunctions.runtime//de.q60.mps.polymorphicfunctions.runtime.GroupPFContext.callFunction(GroupPFContext.java:20)
	at d.q.m.polymorphicfunctions.runtime//de.q60.mps.polymorphicfunctions.runtime.ContextPFContext.callFunction(ContextPFContext.java:22)
	at d.q.m.polymorphicfunctions.runtime//de.q60.mps.polymorphicfunctions.runtime.GroupPFContext.callFunction(GroupPFContext.java:20)
	at d.q.m.polymorphicfunctions.runtime//de.q60.mps.polymorphicfunctions.runtime.AbstractPFContext.callFunction(AbstractPFContext.java:11)
	at d.q.m.explorer.impl//de.q60.mps.explorer.impl.pf.PF_EditorCells$1$1.groupCall(PF_EditorCells.java:83)
	at d.q.m.explorer.impl//de.q60.mps.explorer.impl.pf.PF_EditorCells$1.execute(PF_EditorCells.java:85)
	at d.q.m.polymorphicfunctions.runtime//de.q60.mps.polymorphicfunctions.runtime.RecursionProtection.evaluate(RecursionProtection.java:27)
	at d.q.m.polymorphicfunctions.runtime//de.q60.mps.polymorphicfunctions.runtime.DefaultPFContext.lambda$callFunctions$0(DefaultPFContext.java:45)
	at d.q.m.polymorphicfunctions.runtime//de.q60.mps.polymorphicfunctions.runtime.ContextValue.computeWith(ContextValue.java:57)
	at d.q.m.polymorphicfunctions.runtime//de.q60.mps.polymorphicfunctions.runtime.DefaultPFContext.lambda$callFunctions$1(DefaultPFContext.java:45)
	at jetbrains.mps.internal.collections.runtime.impl.SelectingSequence$SelectingIterator.moveToNext(SelectingSequence.java:60)
	at jetbrains.mps.internal.collections.runtime.impl.SelectingSequence$SelectingIterator.hasNext(SelectingSequence.java:32)
	at jetbrains.mps.internal.collections.runtime.IterableUtils.first(IterableUtils.java:58)
	at jetbrains.mps.internal.collections.runtime.AbstractSequence.first(AbstractSequence.java:188)
	at d.q.m.polymorphicfunctions.runtime//de.q60.mps.polymorphicfunctions.runtime.DefaultPFContext.callFunction(DefaultPFContext.java:32)
	at d.q.m.polymorphicfunctions.runtime//de.q60.mps.polymorphicfunctions.runtime.GroupPFContext.callFunction(GroupPFContext.java:20)
	at d.q.m.polymorphicfunctions.runtime//de.q60.mps.polymorphicfunctions.runtime.ContextPFContext.callFunction(ContextPFContext.java:22)
	at d.q.m.polymorphicfunctions.runtime//de.q60.mps.polymorphicfunctions.runtime.AbstractPFContext.callFunction(AbstractPFContext.java:11)
	at d.q.mps.explorer//de.q60.mps.explorer.pf.TraceBuilders_base$1.execute(TraceBuilders_base.java:55)
	at d.q.m.polymorphicfunctions.runtime//de.q60.mps.polymorphicfunctions.runtime.RecursionProtection.evaluate(RecursionProtection.java:27)
	at d.q.m.polymorphicfunctions.runtime//de.q60.mps.polymorphicfunctions.runtime.DefaultPFContext.lambda$callFunctions$0(DefaultPFContext.java:45)
	at d.q.m.polymorphicfunctions.runtime//de.q60.mps.polymorphicfunctions.runtime.ContextValue.computeWith(ContextValue.java:57)
	at d.q.m.polymorphicfunctions.runtime//de.q60.mps.polymorphicfunctions.runtime.DefaultPFContext.lambda$callFunctions$1(DefaultPFContext.java:45)
	at jetbrains.mps.internal.collections.runtime.impl.SelectingSequence$SelectingIterator.moveToNext(SelectingSequence.java:60)
	at jetbrains.mps.internal.collections.runtime.impl.SelectingSequence$SelectingIterator.hasNext(SelectingSequence.java:32)
	at jetbrains.mps.internal.collections.runtime.IterableUtils.first(IterableUtils.java:58)
	at jetbrains.mps.internal.collections.runtime.AbstractSequence.first(AbstractSequence.java:188)
	at d.q.m.polymorphicfunctions.runtime//de.q60.mps.polymorphicfunctions.runtime.DefaultPFContext.callFunction(DefaultPFContext.java:32)
	at d.q.m.polymorphicfunctions.runtime//de.q60.mps.polymorphicfunctions.runtime.GroupPFContext.callFunction(GroupPFContext.java:20)
	at d.q.m.polymorphicfunctions.runtime//de.q60.mps.polymorphicfunctions.runtime.ContextPFContext.callFunction(ContextPFContext.java:22)
	at d.q.m.polymorphicfunctions.runtime//de.q60.mps.polymorphicfunctions.runtime.AbstractPFContext.callFunction(AbstractPFContext.java:11)
	at d.q.mps.explorer//de.q60.mps.explorer.TransformationTraceComponent.loadTrace(TransformationTraceComponent.java:235)
	at d.q.mps.explorer//de.q60.mps.explorer.TransformationTraceComponent.lambda$loadTrace$6(TransformationTraceComponent.java:189)
	at d.q.mps.explorer//de.q60.mps.explorer.TransformationTraceComponent.lambda$new$0(TransformationTraceComponent.java:64)
	at jetbrains.mps.smodel.ActionDispatcher.dispatch(ActionDispatcher.java:98)
	at jetbrains.mps.smodel.ActionDispatcher.lambda$wrap$0(ActionDispatcher.java:135)
	at jetbrains.mps.smodel.LockRunnable.run(LockRunnable.java:60)
	at jetbrains.mps.smodel.PlatformCancelBlock.run(PlatformCancelBlock.java:22)
	at com.intellij.openapi.application.impl.RwLockHolder.runReadAction(RwLockHolder.kt:254)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:840)
	at jetbrains.mps.smodel.WorkbenchModelAccess.runReadAction(WorkbenchModelAccess.java:95)
	at jetbrains.mps.smodel.ModelAccessBase.runReadAction(ModelAccessBase.java:66)
	at d.q.mps.explorer//de.q60.mps.explorer.TransformationTraceComponent.lambda$new$1(TransformationTraceComponent.java:64)
	at d.q.mps.explorer//de.q60.mps.explorer.TransformationTraceComponent.runRead(TransformationTraceComponent.java:210)
	at d.q.mps.explorer//de.q60.mps.explorer.TransformationTraceComponent.loadTrace(TransformationTraceComponent.java:185)
	at d.q.mps.explorer//de.q60.mps.explorer.TransformationTraceComponent.loadTrace(TransformationTraceComponent.java:181)
	at d.q.m.explorer.impl//de.q60.mps.explorer.impl.plugin.CellExplorer_Action.doExecute(CellExplorer_Action.java:72)
	at jetbrains.mps.workbench.action.BaseAction.lambda$actionPerformed$2(BaseAction.java:226)
	at jetbrains.mps.workbench.action.ActionAccess$EmptyAccess.runWithAccess(ActionAccess.java:58)
	at jetbrains.mps.workbench.action.BaseAction.actionPerformed(BaseAction.java:218)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.doPerformActionOrShowPopup(ActionUtil.kt:304)
	at com.intellij.ide.actions.GotoActionAction.lambda$performActionImpl$4(GotoActionAction.java:85)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.performWithActionCallbacks(ActionManagerImpl.kt:1166)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performDumbAwareWithCallbacks(ActionUtil.kt:321)
	at com.intellij.ide.actions.GotoActionAction.performActionImpl(GotoActionAction.java:84)
	at com.intellij.ide.actions.GotoActionAction.lambda$performAction$2(GotoActionAction.java:64)
	at com.intellij.util.concurrency.ContextRunnable.run(ContextRunnable.java:27)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:209)
	at com.intellij.openapi.application.TransactionGuardImpl.access$100(TransactionGuardImpl.java:22)
	at com.intellij.openapi.application.TransactionGuardImpl$1.run(TransactionGuardImpl.java:191)
	at com.intellij.openapi.application.impl.RwLockHolder.runIntendedWriteActionOnCurrentThread(RwLockHolder.kt:204)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:830)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:419)
	at com.intellij.openapi.application.impl.RwLockHolder.runWithEnabledImplicitRead(RwLockHolder.kt:138)
	at com.intellij.openapi.application.impl.RwLockHolder.runWithImplicitRead(RwLockHolder.kt:129)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWithImplicitRead(ApplicationImpl.java:1152)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:81)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:123)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:43)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:792)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:739)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:733)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:761)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.kt:699)
	at com.intellij.ide.IdeEventQueue._dispatchEvent$lambda$12(IdeEventQueue.kt:593)
	at com.intellij.openapi.application.impl.RwLockHolder.runWithoutImplicitRead(RwLockHolder.kt:105)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.kt:593)
	at com.intellij.ide.IdeEventQueue.access$_dispatchEvent(IdeEventQueue.kt:77)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:362)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:361)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:843)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:361)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:356)
	at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$1(IdeEventQueue.kt:1022)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:106)
	at com.intellij.ide.IdeEventQueueKt.performActivity(IdeEventQueue.kt:1022)
	at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$7(IdeEventQueue.kt:356)
	at com.intellij.openapi.application.impl.RwLockHolder.runIntendedWriteActionOnCurrentThread(RwLockHolder.kt:209)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:830)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.kt:398)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)

**Comment by alexanderpann** [comment]
Not reproducible anymore.
