### ISSUE TITLE
java.lang.IllegalAccessError when displaying diagram or auto-layouting 

### ISSUE THREAD

**Issue by norro** [JetBrains/MPS-extensions#138]
In one of our languages to describe activities, we implemented a graphical editor (close to SysML activity diagrams) using de.itemis.mps.editor.diagram + de.itemis.mps.editor.diagram.layout.
When trying to open some of our diagrams (approx. 10 nodes + 15 edges), we get the exception printed below. Some of our simpler diagrams are first displayed correctly, the exception occurs when trying to auto-layout. 
The exception occurs in 2018.1 and 2018.2.5 with latest mbeddr platform builds.

`Failed to create cell for node [root] [...] in [...]: tried to access method com.google.common.collect.Iterators.emptyIterator()Lcom/google/common/collect/UnmodifiableIterator; from class de.cau.cs.kieler.klay.tree.intermediate.NeighborsProcessor$1
java.lang.IllegalAccessError: tried to access method com.google.common.collect.Iterators.emptyIterator()Lcom/google/common/collect/UnmodifiableIterator; from class de.cau.cs.kieler.klay.tree.intermediate.NeighborsProcessor$1
	at de.cau.cs.kieler.klay.tree.intermediate.NeighborsProcessor$1.iterator(NeighborsProcessor.java:92)
	at com.google.common.collect.Iterables$13.apply(Iterables.java:1094)
	at com.google.common.collect.Iterables$13.apply(Iterables.java:1091)
	at com.google.common.collect.Iterators$7.transform(Iterators.java:750)
	at com.google.common.collect.TransformedIterator.next(TransformedIterator.java:47)
	at com.google.common.collect.MultitransformedIterator.hasNext(MultitransformedIterator.java:52)
	at com.google.common.collect.MultitransformedIterator.hasNext(MultitransformedIterator.java:50)
	at com.google.common.collect.MultitransformedIterator.hasNext(MultitransformedIterator.java:53)
	at com.google.common.collect.MultitransformedIterator.hasNext(MultitransformedIterator.java:50)
	at com.google.common.collect.Iterables.isEmpty(Iterables.java:1056)
	at de.cau.cs.kieler.klay.tree.intermediate.NeighborsProcessor.setNeighbors(NeighborsProcessor.java:81)
	at de.cau.cs.kieler.klay.tree.intermediate.NeighborsProcessor.setNeighbors(NeighborsProcessor.java:121)
	at de.cau.cs.kieler.klay.tree.intermediate.NeighborsProcessor.process(NeighborsProcessor.java:60)
	at de.cau.cs.kieler.klay.tree.KlayTree.layout(KlayTree.java:280)
	at de.cau.cs.kieler.klay.tree.KlayTree.doLayout(KlayTree.java:97)
	at de.itemis.mps.editor.diagram.runtime.layout.Tree_TreeLayoutProvider.doLayout(Tree_TreeLayoutProvider.java:42)
	at de.itemis.mps.editor.diagram.runtime.layout.TreeLayouter.doLayout(TreeLayouter.java:13)
	at de.itemis.mps.editor.diagram.runtime.layout.KielerLayouter.layoutOnce(KielerLayouter.java:140)
	at de.itemis.mps.editor.diagram.runtime.layout.KielerLayouter.layout(KielerLayouter.java:127)
	at de.itemis.mps.editor.diagram.runtime.model.DiagramModel$5.run(DiagramModel.java:457)
	at de.itemis.mps.editor.diagram.runtime.model.ScalableEditorCell.withScalingDisabled(ScalableEditorCell.java:27)
	at de.itemis.mps.editor.diagram.runtime.model.DiagramModel.runLayouter(DiagramModel.java:440)
	at de.itemis.mps.editor.diagram.runtime.model.ModelSynchronizer.fromSModel_(ModelSynchronizer.java:326)
	at de.itemis.mps.editor.diagram.runtime.model.ModelSynchronizer$8$1$1.run(ModelSynchronizer.java:220)
	at de.itemis.mps.editor.diagram.runtime.model.ScalableEditorCell.withScalingDisabled(ScalableEditorCell.java:27)
	at de.itemis.mps.editor.diagram.runtime.model.ModelSynchronizer$8$1.run(ModelSynchronizer.java:218)
	at de.itemis.mps.editor.diagram.runtime.DiagramContext.withContext(DiagramContext.java:29)
	at de.itemis.mps.editor.diagram.runtime.DiagramContext.withContext(DiagramContext.java:36)
	at de.itemis.mps.editor.diagram.runtime.model.ModelSynchronizer$8.run(ModelSynchronizer.java:216)
	at jetbrains.mps.smodel.WorkbenchModelAccess.runReadAction(WorkbenchModelAccess.java:71)
	at jetbrains.mps.smodel.ModelAccessBase.runReadAction(ModelAccessBase.java:53)
	at de.itemis.mps.editor.diagram.runtime.model.ModelSynchronizer.fromSModel(ModelSynchronizer.java:214)
	at de.itemis.mps.editor.diagram.runtime.model.DiagramModel$2.run(DiagramModel.java:223)
	at de.itemis.mps.editor.diagram.runtime.model.ScalableEditorCell.withScalingDisabled(ScalableEditorCell.java:27)
	at de.itemis.mps.editor.diagram.runtime.model.DiagramModel.synchronizeRead(DiagramModel.java:221)
	at de.itemis.mps.editor.diagram.runtime.jgraph.RootDiagramECell$4.run(RootDiagramECell.java:149)
	at de.itemis.mps.editor.diagram.runtime.ContextVariables$1.run(ContextVariables.java:40)
	at de.itemis.mps.editor.diagram.runtime.ContextVariables.enterNewContext(ContextVariables.java:30)
	at de.itemis.mps.editor.diagram.runtime.ContextVariables.withValue(ContextVariables.java:37)
	at de.itemis.mps.editor.diagram.runtime.jgraph.BaseDiagramECell.withContextGraph(BaseDiagramECell.java:120)
	at de.itemis.mps.editor.diagram.runtime.jgraph.RootDiagramECell.<init>(RootDiagramECell.java:147)
	at SisML.editor.Block_act0_EditorBuilder_a$3$1$2$1.run(Block_act0_EditorBuilder_a.java:306)
	at de.itemis.mps.editor.diagram.runtime.ContextVariables$1.run(ContextVariables.java:40)
	at de.itemis.mps.editor.diagram.runtime.ContextVariables.enterNewContext(ContextVariables.java:30)
	at de.itemis.mps.editor.diagram.runtime.ContextVariables.withValue(ContextVariables.java:37)
	at SisML.editor.Block_act0_EditorBuilder_a$3$1$2.run(Block_act0_EditorBuilder_a.java:261)
	at de.itemis.mps.editor.diagram.runtime.DiagramContext.withContext(DiagramContext.java:29)
	at de.itemis.mps.editor.diagram.runtime.DiagramContext.withContext(DiagramContext.java:44)
	at SisML.editor.Block_act0_EditorBuilder_a$3$1.invoke(Block_act0_EditorBuilder_a.java:255)
	at de.itemis.mps.editor.diagram.runtime.jgraph.DiagramCreationContext.createDiagram_(DiagramCreationContext.java:56)
	at de.itemis.mps.editor.diagram.runtime.jgraph.DiagramCreationContext$1.run(DiagramCreationContext.java:34)
	at de.itemis.mps.editor.collapsible.runtime.CollapsibleContext.withFactory(CollapsibleContext.java:21)
	at de.itemis.mps.editor.diagram.runtime.jgraph.DiagramCreationContext.createDiagram(DiagramCreationContext.java:32)
	at SisML.editor.Block_act0_EditorBuilder_a$3.run(Block_act0_EditorBuilder_a.java:253)
	at de.itemis.mps.editor.diagram.runtime.EditorUtil.noCaching(EditorUtil.java:139)
	at SisML.editor.Block_act0_EditorBuilder_a.createDiagram_gsrq5a_b0(Block_act0_EditorBuilder_a.java:251)
	at SisML.editor.Block_act0_EditorBuilder_a.createDiagram_gsrq5a_b0_0(Block_act0_EditorBuilder_a.java:326)
	at SisML.editor.Block_act0_EditorBuilder_a.createCollection_gsrq5a_a(Block_act0_EditorBuilder_a.java:96)
	at SisML.editor.Block_act0_EditorBuilder_a.createCell(Block_act0_EditorBuilder_a.java:78)
	at SisML.editor.Block_act0_Editor.createEditorCell(Block_act0_Editor.java:21)
	at jetbrains.mps.nodeEditor.cells.EditorCellFactoryImpl.createCell(EditorCellFactoryImpl.java:130)
	at jetbrains.mps.nodeEditor.cells.EditorCellFactoryImpl.createEditorCell_internal(EditorCellFactoryImpl.java:113)
	at jetbrains.mps.nodeEditor.cells.EditorCellFactoryImpl.createEditorCell(EditorCellFactoryImpl.java:103)
	at jetbrains.mps.nodeEditor.EditorManager.createEditorCell_internal(EditorManager.java:373)
	at jetbrains.mps.nodeEditor.EditorManager.createEditorCell(EditorManager.java:263)
	at jetbrains.mps.nodeEditor.EditorManager.createRootCell(EditorManager.java:115)
	at jetbrains.mps.nodeEditor.updater.UpdateSessionImpl.performUpdate(UpdateSessionImpl.java:156)
	at jetbrains.mps.nodeEditor.updater.UpdaterImpl.lambda$updateRootCell$0(UpdaterImpl.java:134)
	at jetbrains.mps.typesystem.inference.TypeContextManager$Executor.doExecute(TypeContextManager.java:273)
	at jetbrains.mps.typesystem.inference.TypeContextManager$Executor.execute(TypeContextManager.java:243)
	at jetbrains.mps.typesystem.inference.TypeContextManager.runTypecheckingAction(TypeContextManager.java:138)
	at jetbrains.mps.nodeEditor.updater.UpdaterImpl.updateRootCell(UpdaterImpl.java:134)
	at jetbrains.mps.nodeEditor.updater.UpdaterImpl.doUpdate(UpdaterImpl.java:115)
	at jetbrains.mps.nodeEditor.updater.UpdaterImpl.update(UpdaterImpl.java:91)
	at jetbrains.mps.nodeEditor.EditorComponent.rebuildEditorContent(EditorComponent.java:1792)
	at jetbrains.mps.nodeEditor.NodeEditorComponent.rebuildEditorContent(NodeEditorComponent.java:139)
	at SisML.plugin.PushEditorHintsACTShortcut_Action.doExecute(PushEditorHintsACTShortcut_Action.java:52)
	at jetbrains.mps.workbench.action.BaseAction$2.run(BaseAction.java:150)
	at jetbrains.mps.smodel.WorkbenchModelAccess$CommandRunnable.lambda$run$0(WorkbenchModelAccess.java:449)
	at jetbrains.mps.smodel.WriteActionDispatcher.run(WriteActionDispatcher.java:39)
	at jetbrains.mps.smodel.WorkbenchModelAccess.lambda$runWriteAction$1(WorkbenchModelAccess.java:105)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:1010)
	at jetbrains.mps.smodel.WorkbenchModelAccess.runWriteAction(WorkbenchModelAccess.java:113)
	at jetbrains.mps.smodel.WorkbenchModelAccess$CommandRunnable.run(WorkbenchModelAccess.java:446)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:137)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:95)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:85)
	at jetbrains.mps.smodel.WorkbenchModelAccess.runWriteActionInCommand(WorkbenchModelAccess.java:311)
	at jetbrains.mps.smodel.WorkbenchModelAccess.executeCommand(WorkbenchModelAccess.java:307)
	at jetbrains.mps.project.ProjectModelAccess.executeCommand(ProjectModelAccess.java:43)
	at jetbrains.mps.workbench.action.BaseAction.actionPerformed(BaseAction.java:165)
	at com.intellij.openapi.actionSystem.ex.ActionUtil$1.run(ActionUtil.java:220)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:237)
	at com.intellij.openapi.actionSystem.impl.ActionButton.actionPerformed(ActionButton.java:208)
	at com.intellij.openapi.actionSystem.impl.ActionButton.performAction(ActionButton.java:158)
	at com.intellij.openapi.actionSystem.impl.ActionButton.processMouseEvent(ActionButton.java:372)
	at java.awt.Component.processEvent(Component.java:6313)
	at java.awt.Container.processEvent(Container.java:2237)
	at java.awt.Component.dispatchEventImpl(Component.java:4903)
	at java.awt.Container.dispatchEventImpl(Container.java:2295)
	at java.awt.Component.dispatchEvent(Component.java:4725)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4889)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4526)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4467)
	at java.awt.Container.dispatchEventImpl(Container.java:2281)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4725)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:764)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:737)
	at java.awt.EventQueue$4.run(EventQueue.java:735)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:734)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:786)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:723)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:395)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)`

**Comment by norro** [comment]
@slisson any idea, what is happening or any further information I could contribute?

**Comment by norro** [comment]
Works like a charm with today's mbeddr platform build. Thank you!
