### ISSUE TITLE
com.mbeddr.mpsutil.comparator not usable with shadowmodels

### ISSUE THREAD

**Issue by arimer** [JetBrains/MPS-extensions#171]
Currently if you want to test your shadow model implementation and want to compare the output result with `com.mbeddr.mpsutil.comparator` you'll get an 

```
java.lang.UnsupportedOperationException: Not implemented
	at de.q60.mps.shadowmodels.runtime.smodel.NodeToSNodeAdapter.getPropertyNames(NodeToSNodeAdapter.java:444)
	at com.mbeddr.mpsutil.comparator.code.MPSNodeComparator.fillDifferencesOnProperties(MPSNodeComparator.java:93)
```
due to the fact that the `comparator` is still using some deprecated methods (`getPropertyNames()`) from `SNode`.

**Comment by arimer** [comment]
Created a related issue : https://github.com/mbeddr/mbeddr.core/issues/2048
