### ISSUE TITLE
ResultElementAsNode.removeChild() throws UnsupportedOperationException

### ISSUE THREAD

**Issue by arimer** [JetBrains/MPS-extensions#209]
When I try to detach some child from a "shadow node" I receive the following exception:

```
Java.lang.UnsupportedOperationException
	at de.q60.mps.shadowmodels.runtime.engine.ResultElementAsNode.removeChild(ResultElementAsNode.java:88)
	at de.q60.mps.shadowmodels.runtime.smodel.NodeToSNodeAdapter.delete(NodeToSNodeAdapter.java:196)
	at jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations.deleteNode(SNodeOperations.java:492)
	at jetbrains.mps.lang.smodel.generator.smodelAdapter.AttributeOperations.deleteAttribute(AttributeOperations.java:70)
	at jetbrains.mps.lang.smodel.generator.smodelAdapter.AttributeOperations.setAttribute(AttributeOperations.java:79)
	at org.safe4i.patterns.code.plugin.ShadowModelTransformationUtil.removeShadowFlag(ShadowModelTransformationUtil.java:173)
	at org.safe4i.patterns.code.shadowmodel.tests.util.ShadowModelTestUtil$2.invoke(ShadowModelTestUtil.java:48)
	at org.safe4i.patterns.code.shadowmodel.tests.util.ShadowModelTestUtil$2.invoke(ShadowModelTestUtil.java:1)
	at org.safe4i.patterns.code.plugin.ShadowModelTransformationUtil.executeTransformationForNode(ShadowModelTransformationUtil.java:71)
	at org.safe4i.patterns.code.shadowmodel.tests.util.ShadowModelTestUtil.transformAndCompareWithRefs(ShadowModelTestUtil.java:45)
	at org.safe4i.patterns.code.shadowmodel.tests.test.complexFuncTransfo_Test$TestBody.test_applyEmptySecureFunctionForManualMarkerOnFunctionCall(complexFuncTransfo_Test.java:48)
```

**Comment by arimer** [comment]
The whole idea of "shadow-nodes" is that they are read-ony. A direct manipulation of such ouput is not supported. 
In special cases, for example when comparing the output of a shadow model transformation in a testcase, I can still use a `shadowode.copy` to retrieve a node wich is then **not** read only.

**Comment by arimer** [comment]
@slisson  we should then print a better error message that makes it easier to understand why such a manipulation cannot be done.
