### ISSUE TITLE
Another Exception

### ISSUE THREAD

**Issue by markusvoelter** [JetBrains/MPS-extensions#216]
tion: Multiple root elements found at index 0
	at de.q60.mps.shadowmodels.runtime.engine.TransformationResult.getRootElement(TransformationResult.java:190)
	at de.q60.mps.shadowmodels.runtime.engine.CopyNodeToTransformationResult$3.invoke(CopyNodeToTransformationResult.java:98)
	at de.q60.mps.shadowmodels.runtime.engine.CopyNodeToTransformationResult$3.invoke(CopyNodeToTransformationResult.java:1)
	at de.q60.mps.shadowmodels.runtime.engine.TransformationResult$LazyNodeReferenceTarget.resolveNode(TransformationResult.java:638)
	at de.q60.mps.shadowmodels.runtime.engine.ResultElementAsNode.getReferenceTarget(ResultElementAsNode.java:95)
	at de.q60.mps.shadowmodels.runtime.engine.DependencyTrackingNode.getReferenceTarget(DependencyTrackingNode.java:173)
	at de.q60.mps.shadowmodels.runtime.engine.CopyNodeToTransformationResult$2.invoke(CopyNodeToTransformationResult.java:79)
	at de.q60.mps.shadowmodels.runtime.engine.CopyNodeToTransformationResult$2.invoke(CopyNodeToTransformationResult.java:1)
	at de.q60.mps.shadowmodels.runtime.engine.CopyNodeToTransformationResult$3.invoke(CopyNodeToTransformationResult.java:95)
	at de.q60.mps.shadowmodels.runtime.engine.CopyNodeToTransformationResult$3.invoke(CopyNodeToTransformationResult.java:1)
	at de.q60.mps.shadowmodels.runtime.engine.TransformationResult$LazyNodeReferenceTarget.resolveNode(TransformationResult.java:638)
	at de.q60.mps.shadowmodels.runtime.engine.ResultElementAsNode.getReferenceTarget(ResultElementAsNode.java:95)
	at de.q60.mps.shadowmodels.runtime.engine.DependencyTrackingNode.getReferenceTarget(DependencyTrackingNode.java:173)
	at de.q60.mps.shadowmodels.runtime.smodel.ShadowOutputSynchronizerStep1.synchronizeNode(ShadowOutputSynchronizerStep1.java:139)
	at de.q60.mps.shadowmodels.runtime.smodel.ShadowOutputSynchronizerStep1$2.invoke(ShadowOutputSynchronizerStep1.java:124)
	at de.q60.mps.shadowmodels.runtime.smodel.ShadowOutputSynchronizerStep1$2.invoke(ShadowOutputSynchronizerStep1.java:1)
	at de.q60.mps.incremental.runtime.IncrementalEngine$5.invoke(IncrementalEngine.java:257)
	at de.q60.mps.incremental.runtime.DependencyBroadcaster.evaluateWithTracking(DependencyBroadcaster.java:30)
	at de.q60.mps.incremental.runtime.IncrementalEngine.evaluateWithTracking(IncrementalEngine.java:255)
	at de.q60.mps.incremental.runtime.IncrementalEngine$4.invoke(IncrementalEngine.java:224)
	at de.q60.mps.incremental.runtime.IncrementalEngine.cycleProtection(IncrementalEngine.java:245)
	at de.q60.mps.incremental.runtime.IncrementalEngine.evaluate(IncrementalEngine.java:222)
	at de.q60.mps.shadowmodels.runtime.smodel.ShadowOutputSynchronizerStep1.getOutput(ShadowOutputSynchronizerStep1.java:121)
	at de.q60.mps.shadowmodels.runtime.smodel.ShadowOutputSynchronizerStep1$3.select(ShadowOutputSynchronizerStep1.java:176)
	at de.q60.mps.shadowmodels.runtime.smodel.ShadowOutputSynchronizerStep1$3.select(ShadowOutputSynchronizerStep1.java:1)

**Comment by slisson** [comment]
Not reproducible (anymore). The error log (Tools > Shadow Models > Show Error Log) can help debugging this exception.

**Comment by slisson** [comment]
It's caused by the disabled reductions for `RecordType` and `RecordInstance`.
