### ISSUE TITLE
deleting Documentation deletes whole node

### ISSUE THREAD

**Issue by lhartl** [JetBrains/MPS-extensions#274]
We have a concept, that is IDocumentable. Nodes of this concept are displayed as rows in a table (de.slisson.mps.table). One cell contains the documentation. When deleting the first character of the documentation using Backspace, and hitting Backspace again (once or twice), either the whole node is deleted or the following Exception occurrs: 
```
User's action execute method failed. Action: Table Cell Side Delete. Class: de.slisson.mps.tables.plugin.TableCellSideBackspace_Action

java.lang.NullPointerException
	at de.slisson.mps.hacks.editor.SavedCaretPosition.restore(SavedCaretPosition.java:73)
	at de.slisson.mps.hacks.editor.SavedCaretPosition.restore(SavedCaretPosition.java:69)
	at de.slisson.mps.richtext.behavior.Text__BehaviorDescriptor.normalizeStructure_id4Lll81Ty9os(Text__BehaviorDescriptor.java:90)
	at de.slisson.mps.richtext.behavior.Text__BehaviorDescriptor.invokeSpecial0(Text__BehaviorDescriptor.java:168)
	at jetbrains.mps.core.aspects.behaviour.BaseBHDescriptor.invokeSpecial(BaseBHDescriptor.java:348)
	at jetbrains.mps.core.aspects.behaviour.BaseBHDescriptor.invokeVirtual(BaseBHDescriptor.java:307)
	at jetbrains.mps.core.aspects.behaviour.BaseBHDescriptor.invoke(BaseBHDescriptor.java:231)
	at jetbrains.mps.core.aspects.behaviour.SMethodImpl.invoke0(SMethodImpl.java:151)
	at jetbrains.mps.core.aspects.behaviour.SMethodImpl.invoke(SMethodImpl.java:126)
	at de.slisson.mps.richtext.behavior.Text__BehaviorDescriptor.ensureNormalized_id1xf6IA5Se_N(Text__BehaviorDescriptor.java:123)
	at de.slisson.mps.richtext.behavior.Text__BehaviorDescriptor.invokeSpecial0(Text__BehaviorDescriptor.java:176)
	at jetbrains.mps.core.aspects.behaviour.BaseBHDescriptor.invokeSpecial(BaseBHDescriptor.java:348)
	at jetbrains.mps.core.aspects.behaviour.BaseBHDescriptor.invokeVirtual(BaseBHDescriptor.java:307)
	at jetbrains.mps.core.aspects.behaviour.BaseBHDescriptor.invoke(BaseBHDescriptor.java:231)
	at jetbrains.mps.core.aspects.behaviour.SMethodImpl.invoke0(SMethodImpl.java:151)
	at jetbrains.mps.core.aspects.behaviour.SMethodImpl.invoke(SMethodImpl.java:126)
	at de.slisson.mps.richtext.editor.TextCellModifier$1.execute(TextCellModifier.java:76)
	at de.slisson.mps.tables.plugin.TableCellSideBackspace_Action.doExecute(TableCellSideBackspace_Action.java:96)
	at jetbrains.mps.workbench.action.BaseAction$2.run(BaseAction.java:150)
	at jetbrains.mps.smodel.WorkbenchModelAccess$UndoContextSetup.run(WorkbenchModelAccess.java:378)
	at jetbrains.mps.smodel.ActionDispatcher.dispatch(ActionDispatcher.java:85)
	at jetbrains.mps.smodel.ActionDispatcher.lambda$wrap$0(ActionDispatcher.java:107)
	at jetbrains.mps.smodel.ActionDispatcher.dispatch(ActionDispatcher.java:85)
	at jetbrains.mps.smodel.ActionDispatcher.lambda$wrap$0(ActionDispatcher.java:107)
	at jetbrains.mps.smodel.LockRunnable.run(LockRunnable.java:60)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:1054)
	at jetbrains.mps.smodel.TryRunPlatformWriteHelper.runWrite(TryRunPlatformWriteHelper.java:103)
	at jetbrains.mps.smodel.TryRunPlatformWriteHelper.lambda$withPlatformWrite$1(TryRunPlatformWriteHelper.java:96)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:220)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:178)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:168)
	at jetbrains.mps.smodel.WorkbenchModelAccess.executeCommand(WorkbenchModelAccess.java:299)
	at jetbrains.mps.smodel.ProjectModelAccess2.executeCommand(ProjectModelAccess2.java:35)
	at jetbrains.mps.workbench.action.BaseAction.actionPerformed(BaseAction.java:165)
	at com.intellij.openapi.actionSystem.ex.ActionUtil$1.run(ActionUtil.java:261)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:278)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher$1.performAction(IdeKeyEventDispatcher.java:622)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.lambda$processAction$2(IdeKeyEventDispatcher.java:671)
	at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:195)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:670)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processActionOrWaitSecondStroke(IdeKeyEventDispatcher.java:518)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.inInitState(IdeKeyEventDispatcher.java:473)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.dispatchKeyEvent(IdeKeyEventDispatcher.java:223)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:653)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:373)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```
This is also the case if we use a TODO word we implemented in the documentation. It looks like this: `TODO[...]`. The todo word extends `IWord`. When the cursor is directly on the right side of the opening bracket and Backspace is hit, the expected behavior would be, that the todo disappears, but the whole node (row in table) is deleted.

**Comment by alexanderpann** [comment]
We need to check if the last refactoring of the richtext language already fixed the issue.
