### ISSUE TITLE
ModuleClassLoaderIsDisposedException probably caused by conditional editors

### ISSUE THREAD

**Issue by wsafonov** [JetBrains/MPS-extensions#330]
Since MPS 2020.1 we are encountering this kind of exception quite often:

```
jetbrains.mps.classloading.ModuleClassLoader$ModuleClassLoaderIsDisposedException: ClassLoader of the module 'org.iets3.core.expr.tracing [language]' is disposed and not operable!
	at jetbrains.mps.classloading.ModuleClassLoader.checkNotDisposed(ModuleClassLoader.java:89)
	at jetbrains.mps.classloading.ModuleClassLoader.loadClass(ModuleClassLoader.java:118)
	at jetbrains.mps.classloading.ModuleClassLoader.loadClass(ModuleClassLoader.java:114)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	at org.iets3.core.expr.tracing.editor.BaseConcept_conditionalEditor_Editor_Coloring.createInspectedCell(BaseConcept_conditionalEditor_Editor_Coloring.java:25)
	at jetbrains.mps.nodeEditor.cells.EditorCellFactoryImpl.createCell(EditorCellFactoryImpl.java:138)
	at jetbrains.mps.nodeEditor.cells.EditorCellFactoryImpl.createEditorCell_internal(EditorCellFactoryImpl.java:107)
	at jetbrains.mps.nodeEditor.cells.EditorCellFactoryImpl.createEditorCell(EditorCellFactoryImpl.java:94)
	at jetbrains.mps.nodeEditor.EditorManager.createEditorCell_internal(EditorManager.java:371)
	at jetbrains.mps.nodeEditor.EditorManager.createEditorCell(EditorManager.java:261)
	at jetbrains.mps.nodeEditor.EditorManager.createRootCell(EditorManager.java:115)
	at jetbrains.mps.nodeEditor.updater.UpdateSessionImpl.performUpdate(UpdateSessionImpl.java:157)
	at jetbrains.mps.nodeEditor.updater.UpdaterImpl.lambda$updateRootCell$0(UpdaterImpl.java:134)
	at jetbrains.mps.typechecking.backend.TypecheckingSessionHandler.computeWithSession(TypecheckingSessionHandler.java:61)
	at jetbrains.mps.nodeEditor.updater.UpdaterImpl.updateRootCell(UpdaterImpl.java:134)
	at jetbrains.mps.nodeEditor.updater.UpdaterImpl.doUpdate(UpdaterImpl.java:115)
	at jetbrains.mps.nodeEditor.updater.UpdaterImpl.update(UpdaterImpl.java:91)
	at jetbrains.mps.nodeEditor.EditorComponent.rebuildEditorContent(EditorComponent.java:1781)
	at jetbrains.mps.nodeEditor.EditorComponent.lambda$editNode$5(EditorComponent.java:1051)
	at jetbrains.mps.smodel.WorkbenchModelAccess.runReadAction(WorkbenchModelAccess.java:83)
	at jetbrains.mps.smodel.ModelAccessBase.runReadAction(ModelAccessBase.java:56)
	at jetbrains.mps.nodeEditor.EditorComponent.editNode(EditorComponent.java:1017)
	at jetbrains.mps.nodeEditor.InspectorTool.inspect(InspectorTool.java:210)
	at jetbrains.mps.nodeEditor.NodeEditorComponent.inspect(NodeEditorComponent.java:120)
	at jetbrains.mps.nodeEditor.NodeEditorComponent$1.lambda$selectionChangedTo$0(NodeEditorComponent.java:66)
	at jetbrains.mps.smodel.ActionDispatcher.dispatch(ActionDispatcher.java:88)
	at jetbrains.mps.smodel.WorkbenchModelAccess.lambda$runReadAction$0(WorkbenchModelAccess.java:90)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:864)
	at jetbrains.mps.smodel.WorkbenchModelAccess.runReadAction(WorkbenchModelAccess.java:87)
	at jetbrains.mps.smodel.ModelAccessBase.runReadAction(ModelAccessBase.java:56)
	at jetbrains.mps.nodeEditor.NodeEditorComponent$1.selectionChangedTo(NodeEditorComponent.java:64)
	at jetbrains.mps.nodeEditor.selection.SingularSelectionListenerAdapter.selectionChanged(SingularSelectionListenerAdapter.java:33)
	at jetbrains.mps.nodeEditor.selection.SelectionManagerImpl.doChangeSelection(SelectionManagerImpl.java:217)
	at jetbrains.mps.nodeEditor.selection.SelectionManagerImpl.setSelection(SelectionManagerImpl.java:117)
	at jetbrains.mps.nodeEditor.selection.SelectionManagerImpl.setSelection(SelectionManagerImpl.java:91)
	at jetbrains.mps.nodeEditor.EditorComponent.processCoordSelection(EditorComponent.java:1909)
	at jetbrains.mps.nodeEditor.EditorComponent.processMousePressed(EditorComponent.java:1828)
	at jetbrains.mps.nodeEditor.EditorComponent$8.mousePressed(EditorComponent.java:471)
	at java.desktop/java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:287)
	at java.desktop/java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:287)
	at java.desktop/java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:287)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6647)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3345)
	at java.desktop/java.awt.Component.processEvent(Component.java:6415)
	at java.desktop/java.awt.Container.processEvent(Container.java:2263)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5025)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4857)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4544)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2773)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4857)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:778)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:751)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:749)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:748)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:974)
	at com.intellij.ide.IdeEventQueue.dispatchMouseEvent(IdeEventQueue.java:912)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:844)
	at com.intellij.ide.IdeEventQueue.lambda$null$8(IdeEventQueue.java:449)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:741)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:448)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:831)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:502)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

```

They always come out of the generated conditional editors. So I guess this must be some bug in conditional editors related to a cache not being properly cleaned when modules are reloaded.

**Comment by slisson** [comment]
Looks like EditorCellFactoryImpl.myEditorsCache is the responsible cache. That means it's an MPS issue.
