### ISSUE TITLE
NPE in shadowmodels / modelix

### ISSUE THREAD

**Issue by kbirken** [JetBrains/MPS-extensions#488]
With `de.itemis.mps.extensions.versionNumber=2021.1.2207.af26c21` and MPS 2021.1 (full version numbers below) I am getting a lot of the following NPEs on console. It can be fixed by deactivating shadowmodels, but this won't help if they are actually needed.

The test environment is the current IETS3.core master.

```
java.lang.NullPointerException
	at org.modelix.model.mpsadapters.mps.SModuleAsNode$3.get(SModuleAsNode.java:62)
	at org.modelix.model.mpsadapters.mps.SModuleAsNode$3.get(SModuleAsNode.java:59)
	at org.modelix.model.mpsadapters.mps.TreeElementAsNode.getPropertyValue(TreeElementAsNode.java:119)
	at org.modelix.model.mpsadapters.mps.NodeToSNodeAdapter.getProperty(NodeToSNodeAdapter.java:423)
	at de.q60.mps.shadowmodels.runtime.concurrentrepo.SNodeLoader.updateProperties(SNodeLoader.java:137)
	at de.q60.mps.shadowmodels.runtime.concurrentrepo.SNodeLoader.updateNode(SNodeLoader.java:122)
	at de.q60.mps.shadowmodels.runtime.concurrentrepo.SNodeLoader.updateChildren(SNodeLoader.java:227)
	at de.q60.mps.shadowmodels.runtime.concurrentrepo.RepositoryMirror$5.invoke(RepositoryMirror.java:234)
	at de.q60.mps.shadowmodels.runtime.concurrentrepo.RepositoryMirror$5.invoke(RepositoryMirror.java:229)
	at de.q60.mps.shadowmodels.runtime.model.persistent.SM_PBranch$3.invoke(SM_PBranch.java:146)
	at de.q60.mps.shadowmodels.runtime.model.persistent.SM_PBranch$3.invoke(SM_PBranch.java:144)
	at de.q60.mps.incremental.util.ContextValue.computeWith(ContextValue.java:52)
	at de.q60.mps.shadowmodels.runtime.model.persistent.SM_PBranch.runWrite(SM_PBranch.java:144)
	at de.q60.mps.shadowmodels.runtime.concurrentrepo.RepositoryMirror.updateChildren(RepositoryMirror.java:229)
	at de.q60.mps.shadowmodels.runtime.concurrentrepo.RepositoryMirror.updateModules(RepositoryMirror.java:224)
	at de.q60.mps.shadowmodels.runtime.concurrentrepo.RepositoryMirror$9.run(RepositoryMirror.java:382)
	at jetbrains.mps.smodel.ActionDispatcher.dispatch(ActionDispatcher.java:88)
	at jetbrains.mps.smodel.WorkbenchModelAccess.lambda$runReadAction$0(WorkbenchModelAccess.java:88)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:819)
	at jetbrains.mps.smodel.WorkbenchModelAccess.runReadAction(WorkbenchModelAccess.java:85)
	at jetbrains.mps.smodel.ModelAccessBase.runReadAction(ModelAccessBase.java:56)
	at de.q60.mps.shadowmodels.runtime.concurrentrepo.RepositoryMirror.flush(RepositoryMirror.java:380)
	at de.q60.mps.shadowmodels.runtime.smodel.SM_RepositoryModulesManager.synchronize(SM_RepositoryModulesManager.java:207)
	at de.q60.mps.shadowmodels.runtime.smodel.SM_RepositoryModulesManager$3.run(SM_RepositoryModulesManager.java:130)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

mbeddr.platform and mps.extensions versions:
```
com.mbeddr.platform.major.version=2021
com.mbeddr.platform.minor.version=1
com.mbeddr.platform.build=2021.1.23142.1248361
com.mbeddr.platform.mbeddr.version=2021.1-2021.1.23142.1248361
mps.build.number=MPS-211.7628.1405
mps.date=20210817
mps.build.vcs.number=19fd1e76fbb546cf6562db7c1192e2ff6a670466
mps.teamcity.buildConfName=Binaries
mps.idea.platform.build.number=MPS-211.7628.21
mps.mps.build.counter=1405
mpsBootstrapCore.version.major=2021
mpsBootstrapCore.version.minor=1
mpsBootstrapCore.version.bugfixNr=.3
mpsBootstrapCore.version.eap=
mpsBootstrapCore.version=2021.1
de.itemis.mps.extensions.versionNumber=2021.1.2207.af26c21
```

MPS version:
<img width="371" alt="image" src="https://user-images.githubusercontent.com/1193045/153249153-a34f6ba6-f426-4f65-82bf-cf3571d4e6b9.png">

**Comment by kbirken** [comment]
@slisson Can you have a look? 

BTW: With activated shadowmodels, on the console there are also lots of these messages:

```
2022-02-09 17:52:00,327 [5890731]   WARN - ns.mps.smodel.SModelRepository - Use of SModelRepository.getModelDescriptor(String) is ineffective, please refactor to use SModelReference
2022-02-09 17:52:00,328 [5890732]  ERROR - ns.mps.smodel.SModelRepository - SModelRepository.getInstance() has been deprecated since MPS 3.3 (4 years ago!) and will be removed in MPS 2019.3. Please refactor your co
```
