### ISSUE TITLE
An exception on MPS 2021.3 with latest grammar cells

### ISSUE THREAD

**Issue by const** [JetBrains/MPS-extensions#508]
An exception on MPS 2021.3. It looks like some removed API is used.

Built MPS-Extensions with the latest version on the head: 3f43b1c97291de1dc9f2113e6c2be984462d6141

I created a simple grammar with wrap over baseLanguage Expression, then there are errors on the MPS. 

I would also like installation instructions that are targeted to complete noobs like me, that try to do some tutorials on web and do not yet understand what different things in MPS are. There is build instructions, migrate instructions, but there is no install instructions.

```
Exception while creating substitute actions in class jetbrains.mps.nodeEditor.cellActions.SideTransformSubstituteInfo

java.lang.NoClassDefFoundError: jetbrains/mps/util/Icon2IconResourceAdapter_Deprecated
	at com.mbeddr.mpsutil.grammarcells.runtime.menu.GrammarCellsTransformationMenuPart.createItems(GrammarCellsTransformationMenuPart.java:23)
	at com.mbeddr.mpsutil.grammarcells.runtime.menu.GrammarCellsTransformationMenuPart.createItems(GrammarCellsTransformationMenuPart.java:16)
	at jetbrains.mps.lang.editor.menus.CompositeMenuPart.createItems(CompositeMenuPart.java:36)
	at jetbrains.mps.nodeEditor.menus.transformation.TransformationMenuBase.createMenuItems(TransformationMenuBase.java:43)
	at xsys.language.editor.template_GrammarCellsSideTransformationsMenu.createMenuItems(template_GrammarCellsSideTransformationsMenu.java:39)
	at xsys.language.editor.template_GrammarCellsSideTransformationsMenu.createMenuItems(template_GrammarCellsSideTransformationsMenu.java:23)
	at jetbrains.mps.nodeEditor.menus.transformation.DefaultTransformationMenuItemFactory.createItems(DefaultTransformationMenuItemFactory.java:55)
	at jetbrains.mps.nodeEditor.menus.transformation.DefaultTransformationMenuItemFactory.createItems(DefaultTransformationMenuItemFactory.java:34)
	at jetbrains.mps.nodeEditor.menus.RecursionSafeMenuItemFactory.createItems(RecursionSafeMenuItemFactory.java:51)
	at jetbrains.mps.nodeEditor.menus.transformation.DefaultTransformationMenuContext.createItems(DefaultTransformationMenuContext.java:224)
	at jetbrains.mps.lang.editor.menus.transformation.DefaultConceptMenusTransformationMenuPart.createItemsForConcept(DefaultConceptMenusTransformationMenuPart.java:43)
	at jetbrains.mps.lang.editor.menus.transformation.DefaultConceptMenusTransformationMenuPart.createItemsForConcept(DefaultConceptMenusTransformationMenuPart.java:29)
	at jetbrains.mps.lang.editor.menus.ConceptMenusPart.createItems(ConceptMenusPart.java:43)
	at jetbrains.mps.baseLanguage.editor.Expression_TransformationMenu$2.createItems(Expression_TransformationMenu.java:80)
	at jetbrains.mps.baseLanguage.editor.Expression_TransformationMenu$2.createItems(Expression_TransformationMenu.java:73)
	at jetbrains.mps.lang.editor.menus.CompositeMenuPart.createItems(CompositeMenuPart.java:36)
	at jetbrains.mps.nodeEditor.menus.transformation.TransformationMenuBase.createMenuItems(TransformationMenuBase.java:43)
	at jetbrains.mps.baseLanguage.editor.Expression_TransformationMenu.createMenuItems(Expression_TransformationMenu.java:44)
	at jetbrains.mps.baseLanguage.editor.Expression_TransformationMenu.createMenuItems(Expression_TransformationMenu.java:31)
	at jetbrains.mps.nodeEditor.menus.transformation.DefaultTransformationMenuItemFactory.createItems(DefaultTransformationMenuItemFactory.java:55)
	at jetbrains.mps.nodeEditor.menus.transformation.DefaultTransformationMenuItemFactory.createItems(DefaultTransformationMenuItemFactory.java:34)
	at jetbrains.mps.nodeEditor.menus.RecursionSafeMenuItemFactory.createItems(RecursionSafeMenuItemFactory.java:51)
	at jetbrains.mps.nodeEditor.menus.transformation.DefaultTransformationMenuContext.createItems(DefaultTransformationMenuContext.java:224)
	at jetbrains.mps.lang.editor.menus.transformation.DefaultConceptMenusTransformationMenuPart.createItemsForConcept(DefaultConceptMenusTransformationMenuPart.java:43)
	at jetbrains.mps.lang.editor.menus.transformation.DefaultConceptMenusTransformationMenuPart.createItemsForConcept(DefaultConceptMenusTransformationMenuPart.java:29)
	at jetbrains.mps.lang.editor.menus.ConceptMenusPart.createItems(ConceptMenusPart.java:43)
	at jetbrains.mps.lang.editor.menus.CompositeMenuPart.createItems(CompositeMenuPart.java:36)
	at jetbrains.mps.nodeEditor.menus.transformation.TransformationMenuBase.createMenuItems(TransformationMenuBase.java:43)
	at jetbrains.mps.lang.editor.menus.transformation.ImplicitTransformationMenu.createMenuItems(ImplicitTransformationMenu.java:47)
	at jetbrains.mps.lang.editor.menus.transformation.ImplicitTransformationMenu.createMenuItems(ImplicitTransformationMenu.java:34)
	at jetbrains.mps.nodeEditor.menus.transformation.DefaultTransformationMenuItemFactory.createItems(DefaultTransformationMenuItemFactory.java:55)
	at jetbrains.mps.nodeEditor.menus.transformation.DefaultTransformationMenuItemFactory.createItems(DefaultTransformationMenuItemFactory.java:34)
	at jetbrains.mps.nodeEditor.menus.RecursionSafeMenuItemFactory.createItems(RecursionSafeMenuItemFactory.java:51)
	at jetbrains.mps.nodeEditor.menus.transformation.DefaultTransformationMenuContext.createItems(DefaultTransformationMenuContext.java:224)
	at jetbrains.mps.nodeEditor.cellMenu.TransformationMenuSubstituteInfo.createActions(TransformationMenuSubstituteInfo.java:66)
	at jetbrains.mps.nodeEditor.cellActions.SideTransformSubstituteInfo.createActions(SideTransformSubstituteInfo.java:51)
	at jetbrains.mps.nodeEditor.cellMenu.AbstractNodeSubstituteInfo.lambda$buildActions$0(AbstractNodeSubstituteInfo.java:85)
	at jetbrains.mps.smodel.WorkbenchModelAccess.runReadAction(WorkbenchModelAccess.java:80)
	at jetbrains.mps.smodel.ModelAccessBase.runReadAction(ModelAccessBase.java:56)
	at jetbrains.mps.nodeEditor.cellMenu.AbstractNodeSubstituteInfo.buildActions(AbstractNodeSubstituteInfo.java:84)
	at jetbrains.mps.nodeEditor.cellMenu.AbstractNodeSubstituteInfo.getActionsFromCache(AbstractNodeSubstituteInfo.java:95)
	at jetbrains.mps.nodeEditor.cellMenu.AbstractNodeSubstituteInfo.lambda$getMatchingActions$3(AbstractNodeSubstituteInfo.java:176)
	at jetbrains.mps.util.ComputeRunnable.compute(ComputeRunnable.java:32)
	at jetbrains.mps.util.AbstractComputeRunnable.run(AbstractComputeRunnable.java:27)
	at jetbrains.mps.smodel.WorkbenchModelAccess.runReadAction(WorkbenchModelAccess.java:80)
	at jetbrains.mps.smodel.ModelAccessBase.runReadAction(ModelAccessBase.java:56)
	at jetbrains.mps.smodel.ModelAccessHelper.runReadAction(ModelAccessHelper.java:44)
	at jetbrains.mps.nodeEditor.cellMenu.AbstractNodeSubstituteInfo.getMatchingActions(AbstractNodeSubstituteInfo.java:175)
	at jetbrains.mps.nodeEditor.cellActions.CellAction_SideTransform.canCreateRightTransformHint(CellAction_SideTransform.java:59)
	at jetbrains.mps.nodeEditor.cellActions.CellAction_SideTransform.canExecute(CellAction_SideTransform.java:47)
	at jetbrains.mps.nodeEditor.EditorComponentActions$ActionGetter.compute(EditorComponentActions.java:124)
	at jetbrains.mps.nodeEditor.EditorComponentActions$ActionGetter.compute(EditorComponentActions.java:114)
	at jetbrains.mps.util.ComputeRunnable.compute(ComputeRunnable.java:32)
	at jetbrains.mps.util.AbstractComputeRunnable.run(AbstractComputeRunnable.java:27)
	at jetbrains.mps.smodel.WorkbenchModelAccess.runReadAction(WorkbenchModelAccess.java:80)
	at jetbrains.mps.smodel.ModelAccessBase.runReadAction(ModelAccessBase.java:56)
	at jetbrains.mps.nodeEditor.EditorComponentActions.getComponentAction(EditorComponentActions.java:110)
	at jetbrains.mps.nodeEditor.EditorComponent.getComponentAction(EditorComponent.java:1843)
	at jetbrains.mps.nodeEditor.actions.CellActionExecuter.lambda$getExecutableExecuterFromEditorComponent$3(CellActionExecuter.java:123)
	at jetbrains.mps.nodeEditor.EditorContext.runWithContextCell(EditorContext.java:264)
	at jetbrains.mps.nodeEditor.actions.CellActionExecuter.getExecutableExecuterFromEditorComponent(CellActionExecuter.java:123)
	at jetbrains.mps.nodeEditor.actions.CellActionExecutorFinder.doFindCellActionExecuter(CellActionExecutorFinder.java:72)
	at jetbrains.mps.smodel.WorkbenchModelAccess.runReadAction(WorkbenchModelAccess.java:80)
	at jetbrains.mps.smodel.ModelAccessBase.runReadAction(ModelAccessBase.java:56)
	at jetbrains.mps.nodeEditor.actions.CellActionExecutorFinder.findCellActionExecuter(CellActionExecutorFinder.java:53)
	at jetbrains.mps.nodeEditor.actions.ActionHandlerImpl.findCellActionExecuter(ActionHandlerImpl.java:76)
	at jetbrains.mps.nodeEditor.actions.ActionHandlerImpl.getApplicableCellAction(ActionHandlerImpl.java:63)
	at jetbrains.mps.nodeEditor.IntelligentInputUtil$IntelligentCellProcessor.applyRigthTransform(IntelligentInputUtil.java:280)
	at jetbrains.mps.nodeEditor.IntelligentInputUtil$IntelligentCellProcessor.processCellAtEnd(IntelligentInputUtil.java:211)
	at jetbrains.mps.nodeEditor.IntelligentInputUtil$IntelligentCellProcessor$1.lambda$doCompute$0(IntelligentInputUtil.java:117)
	at jetbrains.mps.typechecking.backend.TypecheckingSessionHandler.computeWithSession(TypecheckingSessionHandler.java:61)
	at jetbrains.mps.nodeEditor.IntelligentInputUtil$IntelligentCellProcessor$1.doCompute(IntelligentInputUtil.java:104)
	at jetbrains.mps.nodeEditor.IntelligentInputUtil$IntelligentCellProcessor$1.doCompute(IntelligentInputUtil.java:96)
	at jetbrains.mps.editor.runtime.commands.EditorComputable.doExecute(EditorComputable.java:43)
	at jetbrains.mps.editor.runtime.commands.EditorCommand.run(EditorCommand.java:55)
	at jetbrains.mps.smodel.WorkbenchModelAccess$UndoContextSetup.run(WorkbenchModelAccess.java:367)
	at jetbrains.mps.smodel.ActionDispatcher.dispatch(ActionDispatcher.java:99)
	at jetbrains.mps.smodel.ActionDispatcher.lambda$wrap$0(ActionDispatcher.java:136)
	at jetbrains.mps.smodel.ActionDispatcher.dispatch(ActionDispatcher.java:99)
	at jetbrains.mps.smodel.ActionDispatcher.lambda$wrap$0(ActionDispatcher.java:136)
	at jetbrains.mps.smodel.LockRunnable.run(LockRunnable.java:60)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:947)
	at jetbrains.mps.smodel.TryRunPlatformWriteHelper.runWrite(TryRunPlatformWriteHelper.java:103)
	at jetbrains.mps.smodel.TryRunPlatformWriteHelper.lambda$withPlatformWrite$1(TryRunPlatformWriteHelper.java:96)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:219)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:174)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:164)
	at jetbrains.mps.smodel.WorkbenchModelAccess.executeCommand(WorkbenchModelAccess.java:302)
	at jetbrains.mps.smodel.ProjectModelAccess2.executeCommand(ProjectModelAccess2.java:35)
	at jetbrains.mps.nodeEditor.IntelligentInputUtil$IntelligentCellProcessor.processCell(IntelligentInputUtil.java:122)
	at jetbrains.mps.nodeEditor.IntelligentInputUtil.processCell(IntelligentInputUtil.java:53)
	at jetbrains.mps.nodeEditor.cells.EditorCell_Label.doProcessKeyTyped(EditorCell_Label.java:488)
	at jetbrains.mps.nodeEditor.cells.EditorCell_Basic.processKeyTyped(EditorCell_Basic.java:433)
	at jetbrains.mps.nodeEditor.EditorComponentKeyboardHandler.processKeyTyped(EditorComponentKeyboardHandler.java:72)
	at jetbrains.mps.nodeEditor.EditorComponent.processKeyTyped(EditorComponent.java:2614)
	at jetbrains.mps.nodeEditor.EditorComponent$9.keyTyped(EditorComponent.java:538)
	at java.desktop/java.awt.AWTEventMulticaster.keyTyped(AWTEventMulticaster.java:248)
	at java.desktop/java.awt.Component.processKeyEvent(Component.java:6609)
	at java.desktop/javax.swing.JComponent.processKeyEvent(JComponent.java:2852)
	at java.desktop/java.awt.Component.processEvent(Component.java:6431)
	at java.desktop/java.awt.Container.processEvent(Container.java:2263)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5029)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4861)
	at java.desktop/java.awt.KeyboardFocusManager.redispatchEvent(KeyboardFocusManager.java:1962)
	at java.desktop/java.awt.DefaultKeyboardFocusManager.dispatchKeyEvent(DefaultKeyboardFocusManager.java:881)
	at java.desktop/java.awt.DefaultKeyboardFocusManager.preDispatchKeyEvent(DefaultKeyboardFocusManager.java:1164)
	at java.desktop/java.awt.DefaultKeyboardFocusManager.typeAheadAssertions(DefaultKeyboardFocusManager.java:1020)
	at java.desktop/java.awt.DefaultKeyboardFocusManager.dispatchEvent(DefaultKeyboardFocusManager.java:844)
	at com.intellij.ide.IdeKeyboardFocusManager.dispatchEvent(IdeKeyboardFocusManager.java:42)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:4910)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2790)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4861)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:778)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:751)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:749)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:748)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:891)
	at com.intellij.ide.IdeEventQueue.dispatchKeyEvent(IdeEventQueue.java:807)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:754)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:447)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:818)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:446)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:805)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:498)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: jetbrains.mps.classloading.ModuleClassNotFoundException: Unable to load class: 'jetbrains.mps.util.Icon2IconResourceAdapter_Deprecated' using ModuleClassLoader of the 'com.mbeddr.mpsutil.grammarcells.runtime' module
	at jetbrains.mps.classloading.ModuleClassLoader.createCLNFException(ModuleClassLoader.java:169)
	at jetbrains.mps.classloading.ModuleClassLoader.getClassFromCache(ModuleClassLoader.java:184)
	at jetbrains.mps.classloading.ModuleClassLoader.loadClass(ModuleClassLoader.java:127)
	at jetbrains.mps.classloading.ModuleClassLoader.loadClass(ModuleClassLoader.java:117)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 139 more
```

**Comment by alexanderpann** [comment]
I remember migrating away from this class and I haven't seen this exception since. This is not an issue anymore.
