### ISSUE TITLE
Diagram: Stackoverflow in getToolTipAt

### ISSUE THREAD

**Issue by alexanderpann** [JetBrains/MPS-extensions#568]
```
java.lang.StackOverflowError
	at jetbrains.mps.nodeEditor.cells.EditorCell_Basic.findLeaf(EditorCell_Basic.java:533)
	at jetbrains.mps.nodeEditor.cells.EditorCell_Collection.findLeaf(EditorCell_Collection.java:730)
	at jetbrains.mps.nodeEditor.cells.EditorCell_Collection.findLeaf(EditorCell_Collection.java:730)
	at jetbrains.mps.nodeEditor.cells.EditorCell_Collection.findLeaf(EditorCell_Collection.java:730)
	at jetbrains.mps.nodeEditor.cells.EditorCell_Collection.findLeaf(EditorCell_Collection.java:730)
	at jetbrains.mps.nodeEditor.cells.EditorCell_Collection.findLeaf(EditorCell_Collection.java:730)
	at jetbrains.mps.nodeEditor.cells.EditorCell_Collection.findLeaf(EditorCell_Collection.java:730)
	at jetbrains.mps.nodeEditor.cells.EditorCell_Collection.findLeaf(EditorCell_Collection.java:730)
	at jetbrains.mps.nodeEditor.cells.EditorCell_Collection.findLeaf(EditorCell_Collection.java:730)
	at de.itemis.mps.editor.diagram.runtime.jgraph.MyGraphComponent.findLeafAtPosition(MyGraphComponent.java:164)
	at de.itemis.mps.editor.diagram.runtime.jgraph.RootDiagramECell.getTooltipAt(RootDiagramECell.java:636)
	at de.itemis.mps.editor.diagram.runtime.jgraph.RootDiagramECell.getTooltipAt(RootDiagramECell.java:652)
	at de.itemis.mps.editor.diagram.runtime.jgraph.RootDiagramECell.getTooltipAt(RootDiagramECell.java:652)
	at de.itemis.mps.editor.diagram.runtime.jgraph.RootDiagramECell.getTooltipAt(RootDiagramECell.java:652)
	at de.itemis.mps.editor.diagram.runtime.jgraph.RootDiagramECell.getTooltipAt(RootDiagramECell.java:652)
	at de.itemis.mps.editor.diagram.runtime.jgraph.RootDiagramECell.getTooltipAt(RootDiagramECell.java:652)
	at de.itemis.mps.editor.diagram.runtime.jgraph.RootDiagramECell.getTooltipAt(RootDiagramECell.java:652)
	at de.itemis.mps.editor.diagram.runtime.jgraph.RootDiagramECell.getTooltipAt(RootDiagramECell.java:652)
	at de.itemis.mps.editor.diagram.runtime.jgraph.RootDiagramECell.getTooltipAt(RootDiagramECell.java:652)
	at de.itemis.mps.editor.diagram.runtime.jgraph.RootDiagramECell.getTooltipAt(RootDiagramECell.java:652)
```

**Comment by alexanderpann** [comment]
The recursive call is [here](http://127.0.0.1:63320/node?ref=r%3A7fc96130-6279-4a55-aeeb-422a6879539d%28de.itemis.mps.editor.diagram.runtime.jgraph%29%2F7561794385527507731). Maybe two diagram cells that want to show each other in a tooltip?

**Comment by alexanderpann** [comment]
Not reproducible. I only saw another instance where a tooltip was used inside a tooltip. There is nothing we can do about this problem.
