### ISSUE TITLE
Exception when editing documentation with com.mbeddr.doc

### ISSUE THREAD

**Issue by alexanderpann** [JetBrains/MPS-extensions#849]
```
java.lang.IllegalArgumentException : Argument for @NotNull parameter 'conceptNode' of jetbrains/mps/smodel/adapter/MetaAdapterByDeclaration.getConcept must not be null
java.lang.IllegalArgumentException: Argument for @NotNull parameter 'conceptNode' of jetbrains/mps/smodel/adapter/MetaAdapterByDeclaration.getConcept must not be null
at jetbrains.mps.smodel.adapter.MetaAdapterByDeclaration.$$$reportNull$$$0(MetaAdapterByDeclaration.java)
at jetbrains.mps.smodel.adapter.MetaAdapterByDeclaration.getConcept(MetaAdapterByDeclaration.java)
at de.slisson.mps.richtext.runtime.WordCellSubstituteInfo$1.accept(WordCellSubstituteInfo.java:48)
at de.slisson.mps.richtext.runtime.WordCellSubstituteInfo$1.accept(WordCellSubstituteInfo.java:46)
at jetbrains.mps.internal.collections.runtime.IWhereFilter.invoke(IWhereFilter.java:12)
at jetbrains.mps.internal.collections.runtime.IWhereFilter.invoke(IWhereFilter.java:7)
at jetbrains.mps.internal.collections.runtime.impl.FilteringSequence$FilteringIterator.moveToNext(FilteringSequence.java:63)
at jetbrains.mps.internal.collections.runtime.impl.FilteringSequence$FilteringIterator.hasNext(FilteringSequence.java:34)
at jetbrains.mps.internal.collections.runtime.impl.SelectingSequence$SelectingIterator.moveToNext(SelectingSequence.java:59)
at jetbrains.mps.internal.collections.runtime.impl.SelectingSequence$SelectingIterator.hasNext(SelectingSequence.java:32)
at jetbrains.mps.internal.collections.runtime.ListSequence.fromIterable(ListSequence.java:122)
at jetbrains.mps.internal.collections.runtime.AbstractSequence.toListSequence(AbstractSequence.java:215)
at de.slisson.mps.richtext.runtime.WordCellSubstituteInfo.wrap(WordCellSubstituteInfo.java:62)
at de.slisson.mps.richtext.runtime.WordCellSubstituteInfo.getMatchingActions(WordCellSubstituteInfo.java:46)
at jetbrains.mps.nodeEditor.cellMenu.NodeSubstituteInfoFilterDecorator.lambda$getMatchingActions$0(NodeSubstituteInfoFilterDecorator.java:56)
at jetbrains.mps.util.ComputeRunnable.compute(ComputeRunnable.java:32)
at jetbrains.mps.util.AbstractComputeRunnable.run(AbstractComputeRunnable.java:27)
at jetbrains.mps.smodel.WorkbenchModelAccess.runReadAction(WorkbenchModelAccess.java:80)
at jetbrains.mps.smodel.ModelAccessBase.runReadAction(ModelAccessBase.java:56)
at jetbrains.mps.smodel.ModelAccessHelper.runReadAction(ModelAccessHelper.java:44)
at jetbrains.mps.nodeEditor.cellMenu.NodeSubstituteInfoFilterDecorator.getMatchingActions(NodeSubstituteInfoFilterDecorator.java:50)
at jetbrains.mps.nodeEditor.cellMenu.NodeSubstituteChooser.lambda$getMatchingActions$1(NodeSubstituteChooser.java:347)
at jetbrains.mps.typechecking.backend.TypecheckingSessionHandler.computeWithSession(TypecheckingSessionHandler.java:61)
at jetbrains.mps.nodeEditor.cellMenu.NodeSubstituteChooser.getMatchingActions(NodeSubstituteChooser.java:346)
at jetbrains.mps.nodeEditor.cellMenu.NodeSubstituteChooser.doRebuildMenuEntries(NodeSubstituteChooser.java:374)
at jetbrains.mps.smodel.WorkbenchModelAccess.runReadAction(WorkbenchModelAccess.java:80)
at jetbrains.mps.smodel.ModelAccessBase.runReadAction(ModelAccessBase.java:56)
at jetbrains.mps.nodeEditor.cellMenu.NodeSubstituteChooser.rebuildMenuEntries(NodeSubstituteChooser.java:359)
at jetbrains.mps.nodeEditor.cellMenu.NodeSubstituteChooser.processEventAfterPatternEditor(NodeSubstituteChooser.java:515)
at jetbrains.mps.nodeEditor.cellMenu.NodeSubstituteChooser.selectionChanged(NodeSubstituteChooser.java:167)
at jetbrains.mps.nodeEditor.EditorComponent.lambda$createUI$4(EditorComponent.java:765)
at jetbrains.mps.nodeEditor.selection.SelectionManagerImpl.doChangeSelection(SelectionManagerImpl.java:219)
at jetbrains.mps.nodeEditor.selection.SelectionManagerImpl.setSelection(SelectionManagerImpl.java:119)
at jetbrains.mps.nodeEditor.cells.EditorCell_Label.fireSelectionChanged(EditorCell_Label.java:845)
at jetbrains.mps.nodeEditor.cells.EditorCell_Label$ModifyTextCommand.commit(EditorCell_Label.java:1243)
at jetbrains.mps.nodeEditor.cells.EditorCell_Label$ModifyTextCommand.doCompute(EditorCell_Label.java:1213)
at jetbrains.mps.nodeEditor.cells.EditorCell_Label$ModifyTextCommand.doCompute(EditorCell_Label.java:1180)
at jetbrains.mps.editor.runtime.commands.EditorComputable.doExecute(EditorComputable.java:43)
at jetbrains.mps.editor.runtime.commands.EditorCommand.run(EditorCommand.java:55)
at jetbrains.mps.smodel.WorkbenchModelAccess$UndoContextSetup.run(WorkbenchModelAccess.java:367)
at jetbrains.mps.smodel.ActionDispatcher.dispatch(ActionDispatcher.java:98)
at jetbrains.mps.smodel.ActionDispatcher.lambda$wrap$0(ActionDispatcher.java:135)
at jetbrains.mps.smodel.ActionDispatcher.dispatch(ActionDispatcher.java:98)
at jetbrains.mps.smodel.ActionDispatcher.lambda$wrap$0(ActionDispatcher.java:135)
at jetbrains.mps.smodel.LockRunnable.run(LockRunnable.java:60)
at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:1023)
at jetbrains.mps.smodel.TryRunPlatformWriteHelper.runWrite(TryRunPlatformWriteHelper.java:103)
at jetbrains.mps.smodel.TryRunPlatformWriteHelper.lambda$withPlatformWrite$1(TryRunPlatformWriteHelper.java:96)
at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:219)
at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:174)
at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:164)
at jetbrains.mps.smodel.WorkbenchModelAccess.executeCommand(WorkbenchModelAccess.java:302)
at jetbrains.mps.smodel.ProjectModelAccess2.executeCommand(ProjectModelAccess2.java:35)
at jetbrains.mps.nodeEditor.cells.EditorCell_Label.doProcessKeyTyped(EditorCell_Label.java:480)
at de.slisson.mps.editor.multiline.cells.EditorCell_Word.doProcessKeyTyped(EditorCell_Word.java:168)
at jetbrains.mps.nodeEditor.cells.EditorCell_Basic.processKeyTyped(EditorCell_Basic.java:431)
at jetbrains.mps.nodeEditor.EditorComponentKeyboardHandler.processKeyTyped(EditorComponentKeyboardHandler.java:72)
at jetbrains.mps.nodeEditor.EditorComponent.processKeyTyped(EditorComponent.java:2619)
at jetbrains.mps.nodeEditor.EditorComponent$9.keyTyped(EditorComponent.java:538)
at java.desktop/java.awt.AWTEventMulticaster.keyTyped(AWTEventMulticaster.java:248)
at java.desktop/java.awt.Component.processKeyEvent(Component.java:6603)
at java.desktop/javax.swing.JComponent.processKeyEvent(JComponent.java:2899)
at java.desktop/java.awt.Component.processEvent(Component.java:6425)
at java.desktop/java.awt.Container.processEvent(Container.java:2266)
at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5022)
at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
at java.desktop/java.awt.Component.dispatchEvent(Component.java:4854)
at java.desktop/java.awt.KeyboardFocusManager.redispatchEvent(KeyboardFocusManager.java:1964)
at java.desktop/java.awt.DefaultKeyboardFocusManager.dispatchKeyEvent(DefaultKeyboardFocusManager.java:886)
at java.desktop/java.awt.DefaultKeyboardFocusManager.preDispatchKeyEvent(DefaultKeyboardFocusManager.java:1166)
at java.desktop/java.awt.DefaultKeyboardFocusManager.typeAheadAssertions(DefaultKeyboardFocusManager.java:1023)
at java.desktop/java.awt.DefaultKeyboardFocusManager.dispatchEvent(DefaultKeyboardFocusManager.java:849)
at com.intellij.ide.IdeKeyboardFocusManager.lambda$dispatchEvent$0(IdeKeyboardFocusManager.java:48)
at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:105)
at com.intellij.ide.IdeEventQueue.performActivity(IdeEventQueue.java:624)
at com.intellij.ide.IdeKeyboardFocusManager.dispatchEvent(IdeKeyboardFocusManager.java:48)
at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:4903)
at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2802)
at java.desktop/java.awt.Component.dispatchEvent(Component.java:4854)
at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:781)
at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:730)
at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:724)
at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:754)
at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:752)
at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:751)
at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:918)
at com.intellij.ide.IdeEventQueue.dispatchKeyEvent(IdeEventQueue.java:827)
at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:760)
at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:450)
at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:791)
at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:449)
at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:113)
at com.intellij.ide.IdeEventQueue.performActivity(IdeEventQueue.java:624)
at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:447)
at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:881)
at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:493)
at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
```

**Comment by alexanderpann** [comment]
This issue is obsolete because this code doesn't exist anymore.
