### ISSUE TITLE
Extension was already added: com.mbeddr.mpsutil.projectview.runtime.tree.CustomProjectView

### ISSUE THREAD

**Issue by digital-ember** [JetBrains/MPS-extensions#905]
I'm getting this exception twice every time I start MPS. Can this be avoided? 
I use 2023.2.2872.2b32f29 a sa global library.

```
java.lang.Throwable: Extension was already added: com.mbeddr.mpsutil.projectview.runtime.tree.CustomProjectView@644ee42f        at com.intellij.openapi.diagnostic.Logger.error(Logger.java:376)
        at com.intellij.openapi.extensions.impl.ExtensionPointImpl.doRegisterExtension(ExtensionPointImpl.java:145)
        at com.intellij.openapi.extensions.impl.ExtensionPointImpl.registerExtension(ExtensionPointImpl.java:119)
        at com.intellij.openapi.extensions.impl.ExtensionPointImpl.registerExtension(ExtensionPointImpl.java:113)
        at c.m.m.projectview.runtime//com.mbeddr.mpsutil.projectview.runtime.ProjectViewManager.activateView(ProjectViewManager.java:150)
        at c.m.m.projectview.runtime//com.mbeddr.mpsutil.projectview.runtime.ProjectViewManager.lambda$syncViews$4(ProjectViewManager.java:119)
        at jetbrains.mps.ide.ThreadUtils$LogExceptionsRunnable.run(ThreadUtils.java:92)
        at jetbrains.mps.ide.ThreadUtils.runInUIThreadNoWait(ThreadUtils.java:69)
        at c.m.m.projectview.runtime//com.mbeddr.mpsutil.projectview.runtime.ProjectViewManager.syncViews(ProjectViewManager.java:110)
        at c.m.m.projectview.runtime//com.mbeddr.mpsutil.projectview.runtime.ProjectViewManager.registerProject(ProjectViewManager.java:60)
        at c.m.m.projectview.runtime//com.mbeddr.mpsutil.projectview.runtime.plugin.ProjectViewProjectPlugin_ProjectPluginPart.init(ProjectViewProjectPlugin_ProjectPluginPart.java:14)
        at jetbrains.mps.plugins.projectplugins.BaseProjectPlugin.initCustomParts(BaseProjectPlugin.java:74)
        at jetbrains.mps.plugins.projectplugins.BaseProjectPlugin.init(BaseProjectPlugin.java:94)
        at jetbrains.mps.plugins.projectplugins.ProjectPluginManager.createPlugin(ProjectPluginManager.java:161)
        at jetbrains.mps.plugins.projectplugins.ProjectPluginManager.createPlugin(ProjectPluginManager.java:54)
        at jetbrains.mps.plugins.BasePluginManager.createPluginChecked(BasePluginManager.java:156)
        at jetbrains.mps.plugins.BasePluginManager.createPlugins(BasePluginManager.java:143)
        at jetbrains.mps.plugins.BasePluginManager.loadPlugins(BasePluginManager.java:73)
        at jetbrains.mps.plugins.PluginLoaderRegistry.loadContributors(PluginLoaderRegistry.java:206)
        at jetbrains.mps.plugins.PluginLoaderRegistry$UpdatingTask.addLoaders(PluginLoaderRegistry.java:579)
        at jetbrains.mps.plugins.PluginLoaderRegistry$UpdatingTask.update(PluginLoaderRegistry.java:540)
        at jetbrains.mps.plugins.PluginLoaderRegistry$UpdatingTask.lambda$run$1(PluginLoaderRegistry.java:452)
```

```
java.lang.Throwable: Extension was already added: com.mbeddr.mpsutil.projectview.runtime.tree.CustomProjectView@36b5034a
        at com.intellij.openapi.diagnostic.Logger.error(Logger.java:376)
        at com.intellij.openapi.extensions.impl.ExtensionPointImpl.doRegisterExtension(ExtensionPointImpl.java:145)
        at com.intellij.openapi.extensions.impl.ExtensionPointImpl.registerExtension(ExtensionPointImpl.java:119)
        at com.intellij.openapi.extensions.impl.ExtensionPointImpl.registerExtension(ExtensionPointImpl.java:113)
        at c.m.m.projectview.runtime//com.mbeddr.mpsutil.projectview.runtime.ProjectViewManager.activateView(ProjectViewManager.java:150)
        at c.m.m.projectview.runtime//com.mbeddr.mpsutil.projectview.runtime.ProjectViewManager.lambda$syncViews$4(ProjectViewManager.java:119)
        at jetbrains.mps.ide.ThreadUtils$LogExceptionsRunnable.run(ThreadUtils.java:92)
        at jetbrains.mps.ide.ThreadUtils.runInUIThreadNoWait(ThreadUtils.java:69)
        at c.m.m.projectview.runtime//com.mbeddr.mpsutil.projectview.runtime.ProjectViewManager.syncViews(ProjectViewManager.java:110)
        at c.m.m.projectview.runtime//com.mbeddr.mpsutil.projectview.runtime.ProjectViewManager.registerProject(ProjectViewManager.java:60)
        at c.m.m.projectview.runtime//com.mbeddr.mpsutil.projectview.runtime.plugin.ProjectViewProjectPlugin_ProjectPluginPart.init(ProjectViewProjectPlugin_ProjectPluginPart.java:14)
        at jetbrains.mps.plugins.projectplugins.BaseProjectPlugin.initCustomParts(BaseProjectPlugin.java:74)
        at jetbrains.mps.plugins.projectplugins.BaseProjectPlugin.init(BaseProjectPlugin.java:94)
        at jetbrains.mps.plugins.projectplugins.ProjectPluginManager.createPlugin(ProjectPluginManager.java:161)
        at jetbrains.mps.plugins.projectplugins.ProjectPluginManager.createPlugin(ProjectPluginManager.java:54)
        at jetbrains.mps.plugins.BasePluginManager.createPluginChecked(BasePluginManager.java:156)
        at jetbrains.mps.plugins.BasePluginManager.createPlugins(BasePluginManager.java:143)
        at jetbrains.mps.plugins.BasePluginManager.loadPlugins(BasePluginManager.java:73)
        at jetbrains.mps.plugins.PluginLoaderRegistry.loadContributors(PluginLoaderRegistry.java:206)
        at jetbrains.mps.plugins.PluginLoaderRegistry$UpdatingTask.addLoaders(PluginLoaderRegistry.java:579)
        at jetbrains.mps.plugins.PluginLoaderRegistry$UpdatingTask.update(PluginLoaderRegistry.java:540)
        at jetbrains.mps.plugins.PluginLoaderRegistry$UpdatingTask.lambda$run$1(PluginLoaderRegistry.java:452)
        at com.intellij.openapi.application.TransactionGuardImpl$1.run(TransactionGuardImpl.java:194)
        at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:843)
```

**Comment by alexanderpann** [comment]
Can anyone tell me if this issue is still present in 2023.2? I can't reproduce it.
