### ISSUE TITLE
ClassCastException in com.mbeddr.mpsutil.projectview.views.plugin

### ISSUE THREAD

**Issue by arimer** [JetBrains/MPS-extensions#945]
When using platform in Version com.mbeddr:platform:2022.3.24843.4b3a10a from stubs, this exception is popping up on startup.

<details>
  <summary>Stacktrace</summary>

```
Caught exception from the listener com.mbeddr.mpsutil.projectview.runtime.ProjectViewManager@213462f5. Will continue.

java.lang.ClassCastException: class com.mbeddr.mpsutil.projectview.views.plugin.ProjectViewDescriptor cannot be cast to class com.mbeddr.mpsutil.projectview.runtime.IProjectViewDescriptor (com.mbeddr.mpsutil.projectview.views.plugin.ProjectViewDescriptor is in unnamed module of loader jetbrains.mps.classloading.ModuleClassLoader @45807f1; com.mbeddr.mpsutil.projectview.runtime.IProjectViewDescriptor is in unnamed module of loader jetbrains.mps.classloading.ModuleClassLoader @22f84e5e)
	at com.mbeddr.mpsutil.projectview.runtime.ProjectViewManager.getDescriptor(ProjectViewManager.java:249)
	at com.mbeddr.mpsutil.projectview.runtime.ProjectViewManager.loadModule(ProjectViewManager.java:222)
	at com.mbeddr.mpsutil.projectview.runtime.ProjectViewManager.onLoaded(ProjectViewManager.java:67)
	at jetbrains.mps.classloading.ClassLoadingBroadCaster.onLoad(ClassLoadingBroadCaster.java:126)
	at jetbrains.mps.classloading.ClassLoaderManager.lambda$preLoadModules$3(ClassLoaderManager.java:394)
	at jetbrains.mps.classloading.ClassLoaderManager.runTransaction(ClassLoaderManager.java:324)
	at jetbrains.mps.classloading.ClassLoaderManager.preLoadModules(ClassLoaderManager.java:375)
	at jetbrains.mps.classloading.ClassLoaderManager.doReloadModules(ClassLoaderManager.java:565)
	at jetbrains.mps.classloading.ModuleEventsHandler.updateModules(ModuleEventsHandler.java:99)
	at jetbrains.mps.classloading.ModuleEventsHandler.eventsHappened(ModuleEventsHandler.java:123)
	at jetbrains.mps.classloading.ModuleEventsDispatcher.fireModuleEvents(ModuleEventsDispatcher.java:107)
	at jetbrains.mps.classloading.ModuleEventsDispatcher.actionFinished(ModuleEventsDispatcher.java:78)
	at java.base/java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:807)
	at jetbrains.mps.smodel.ActionDispatcher.onExit(ActionDispatcher.java:223)
	at jetbrains.mps.smodel.ActionDispatcher.dispatch(ActionDispatcher.java:115)
	at jetbrains.mps.smodel.ActionDispatcher.lambda$wrap$0(ActionDispatcher.java:136)
	at jetbrains.mps.smodel.LockRunnable.run(LockRunnable.java:60)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:872)
	at jetbrains.mps.smodel.WorkbenchModelAccess.runWriteAction(WorkbenchModelAccess.java:100)
	at jetbrains.mps.smodel.ModelAccessBase.runWriteAction(ModelAccessBase.java:66)
	at jetbrains.mps.library.SLibrary.update(SLibrary.java:131)
	at jetbrains.mps.ide.platform.watching.FileProcessor.update(FileProcessor.java:80)
	at jetbrains.mps.ide.platform.watching.ReloadSession.doReload(ReloadSession.java:83)
	at jetbrains.mps.ide.platform.watching.ReloadManagerComponent$1$1.run(ReloadManagerComponent.java:182)
	at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:429)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:114)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsynchronously$6(CoreProgressManager.java:480)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:252)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:186)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:604)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:679)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:635)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:603)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:173)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:252)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)

```
</details>

**Comment by arimer** [comment]
Still using 2022.2 🙈
